FROM node:20-alpine

WORKDIR /app

COPY shared/eslint/   ./shared/eslint/
COPY shared/prettier/ ./shared/prettier/
RUN cd shared/eslint && npm install

COPY order-service/ ./order-service/
RUN cd order-service && npm ci

WORKDIR /app/order-service

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
